### ISSUE TITLE
Support GitHub package versions with monorepos

### ISSUE THREAD

**Issue by aomarks** [Polymer/tachometer#100]
NPM's `github:` protocol for specifying package versions only works when the top-level of the git repository maps to the NPM package (see https://github.com/npm/npm/issues/2974 which is won't-fix). In the case of monorepos, such as the one for Material Web Components, packages are organized into sub-directories. This means there's no way to use tachometer's `package-version` feature for benchmarking commits of repos like this.

The simplest solution is to write a bash script that makes a few clones of the repo, and then sets the package version to the path of the local clone (plus the package directory). We should at least document this pattern if that's the answer.

We could also think about building some kind of support into tachometer. It would basically do the same thing as above, with temp directories. Not convinced yet it's worth the complexity, maybe we should start with documenting the manual pattern.

cc @e111077

**Comment by Westbrook** [comment]
@aomarks I would love to see some sort of follow up to this.

Comparing to `main` or similar branch would be a great win, and if there is no other path to making that possible that some bash scripting, it would be super helpful to see how you saw that coming together!

Similarly, but not the same, I can easily implement testing against my current branch or against remote versions of the packages in my mono-repo, and it would seem like that Tachometer should be able to support comparing at least those two contexts without extra bash scripting. Being `--package-version=next=@spectrum-web-components/button@current` would already be using a temporary directory to run the test, could something in the realm `--package-version=current` allow for the test to run as if `--package-version` wasn't being used in order to get the comparison. Or maybe there's already a CLI option that I haven't been able to find that does that already?

It's possible that a single unifying approach to this sort of cross-version testing in a monorepo is a better goal than answering the two paths above separately, in which case I'd vote for a CLI path forward (if possible). Where bash scripting required here, I look forward to your thoughts on how you'd pursue that.

**Comment by aomarks** [comment]
This is published in `v0.5.2`, see https://github.com/Polymer/tachometer/blob/master/README.md#swap-npm-dependencies
