### ISSUE TITLE
docs: setting horizon via configuration

### ISSUE THREAD

**Issue by guybedford** [Polymer/tachometer#221]
If setting `horizon` in configuration, it says this is not allowed. If providing `--horizon` along with `--config` it again says this is not allowed.

The docs for the configuration instead use `"autoSampleConditions"` which is not documented and I wasn't able to locate this in the source code either.

**Comment by aomarks** [comment]
Sorry for the confusion. The CLI flag is `--horizon`, while the JSON config setting is **`horizons`** (note plural). Fixed in https://github.com/Polymer/tachometer/pull/224 (along with a bunch of other docs improvements).

The `autoSampleConditions` name you saw is a mistake leftover when I was considering an alternate name. Which reminds me, "horizons" actually is a pretty confusing name, so I've also just sent out https://github.com/Polymer/tachometer/pull/225 to change this setting to `--auto-sample-conditions` and `autoSampleConditions`. Will be backwards compatible with the old name.

**Comment by Eldeloro1** [comment]
> If setting `horizon` in configuration, it says this is not allowed. If providing `--horizon` along with `--config` it again says this is not allowed.
> 
> The docs for the configuration instead use `"autoSampleConditions"` which is not documented and I wasn't able to locate this in the source code either.
