### ISSUE TITLE
Firefox use default profile

### ISSUE THREAD

**Issue by guybedford** [Polymer/tachometer#222]
It can be useful to have firefox use the default profile by default, specifically when configuring local certificates for network requests.

Perhaps consider changing this default?

**Comment by guybedford** [comment]
I'm currently trawling through selenium / Firefox docs working out how to change this, even just documenting it could help.

**Comment by aomarks** [comment]
My thinking has been that it makes to have a clean-room browser by default, so that extensions etc. won't interfere with the benchmark. (This is also the Selenium default). I could definitely see a "useDefaultProfile: true" or similar setting, though, which would know how to do that for all browsers.

We do have instructions for changing profiles in Chrome using the `addArguments` setting: https://github.com/Polymer/tachometer#profiles

However, it seems that we don't currently support `addArguments` for Firefox. I'll add that, test out profile switching, and update the docs.

**Comment by guybedford** [comment]
> However, it seems that we don't currently support addArguments for Firefox. I'll add that, test out profile switching, and update the docs.

This would be an absolutely massive help thanks for considering it. Even just persisting a unique profile that can be shared between runs would be fine as well, the annoying part is having to uniquely update the certificate chain on each run.

**Comment by aomarks** [comment]
I've added a new `browser.profile` setting in https://github.com/Polymer/tachometer/pull/226, which works for Firefox and Chrome. I also fixed the `addArguments` bug, though you shouldn't need that now that `browser.profile` exists.

I also published a pre-release version so you can test this out early: `npm i tachometer@^0.5.10-pre.0`

Would love to hear if it works for you. It worked for me so far on macOS and Linux.

**Comment by aomarks** [comment]
> I also published a pre-release version so you can test this out early: `npm i tachometer@^0.5.10-pre.0`.

Just released `0.5.10` final FYI
